=== AubinMahe/jsontools/json-xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="object"  type="objectType"  />
  <xs:element name="array"   type="arrayType"   />
  <xs:element name="boolean" type="booleanType" />
  <xs:element name="integer" type="integerType" />
  <xs:element name="double"  type="doubleType"  />
  <xs:element name="string"  type="xs:string"   />
  <xs:element name="null"    type="xs:string"   />

  <xs:complexType name="propertyType">
    <xs:choice>
      <xs:element ref="object"  />
      <xs:element ref="array"   />
      <xs:element ref="boolean" />
      <xs:element ref="integer" />
      <xs:element ref="double"  />
      <xs:element ref="string"  />
      <xs:element ref="null"    />
    </xs:choice>
    <xs:attribute type="xs:string" name="name"/>
  </xs:complexType>

  <xs:complexType name="objectType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="property" type="propertyType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="arrayType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:choice>
        <xs:element ref="object"  />
        <xs:element ref="array"   />
        <xs:element ref="boolean" />
        <xs:element ref="integer" />
        <xs:element ref="double"  />
        <xs:element ref="string"  />
        <xs:element ref="null"    />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="booleanType">
    <xs:attribute name="value" type="xs:boolean" />
  </xs:complexType>
  
  <xs:complexType name="integerType">
    <xs:attribute name="value" type="xs:long" />
  </xs:complexType>
  
  <xs:complexType name="doubleType">
    <xs:attribute name="value" type="xs:float" />
  </xs:complexType>
  
  <xs:complexType name="stringType" />
  
  <xs:complexType name="nullType" />
  
</xs:schema>

=== AubinMahe/jsontools/data/object.xml
<?xml version="1.0" encoding="UTF-8"?>
<object xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../json-xml.xsd">
   <property name="subs">
      <array>
         <object>
            <property name="value">
               <integer value="1" />
            </property>
         </object>
         <object>
            <property name="value">
               <integer value="2" />
            </property>
         </object>
         <object>
            <property name="value">
               <integer value="3" />
            </property>
         </object>
      </array>
   </property>
   <property name="name">
      <string>jsontools</string>
   </property>
   <property name="keywords">
      <string>json</string>
   </property>
   <property name="author">
      <string>Aubin Mahé, © 2021 (UTF-8 test string)</string>
   </property>
   <property name="description">
      <string>Tree oriented: each node is strongly typed.
Dynamically allocated: like a DOM XML parser, this parser reads all the data in memory, chunks allocated by calloc and strdup.
Reading a file or a character buffer.
Getting a JST_Element by its path.
Creates, read, updates or deletes a property of an object or an item of an array.</string>
   </property>
   <property name="repository">
      <object>
         <property name="type">
            <string>git</string>
         </property>
         <property name="url">
            <string>https://github.com/AubinMahe/jsontools</string>
         </property>
         <property name="examples">
            <array>
               <object>
                  <property name="integer">
                     <integer value="1" />
                  </property>
                  <property name="double">
                     <double value="3.14" />
                  </property>
                  <property name="boolean">
                     <boolean value="false" />
                  </property>
                  <property name="subs">
                     <array>
                        <object>
                           <property name="value">
                              <integer value="1" />
                           </property>
                        </object>
                        <object>
                           <property name="value">
                              <integer value="2" />
                           </property>
                        </object>
                        <object>
                           <property name="value">
                              <integer value="3" />
                           </property>
                        </object>
                     </array>
                  </property>
                  <property name="values">
                     <array>
                        <integer value="9" />
                        <integer value="8" />
                        <integer value="7" />
                     </array>
                  </property>
               </object>
               <object>
                  <property name="integer">
                     <integer value="2" />
                  </property>
                  <property name="double">
                     <double value="6.28" />
                  </property>
                  <property name="boolean">
                     <boolean value="true" />
                  </property>
               </object>
               <object>
                  <property name="integer">
                     <integer value="3" />
                  </property>
                  <property name="double">
                     <double value="9.32" />
                  </property>
                  <property name="boolean">
                     <boolean value="false" />
                  </property>
                  <property name="subs">
                     <array>
                        <object>
                           <property name="value">
                              <integer value="1" />
                           </property>
                        </object>
                        <object>
                           <property name="value">
                              <integer value="4" />
                           </property>
                        </object>
                        <object>
                           <property name="value">
                              <integer value="5" />
                           </property>
                        </object>
                        <object>
                           <property name="value">
                              <integer value="6" />
                           </property>
                        </object>
                        <object>
                           <property name="value">
                              <integer value="7" />
                           </property>
                        </object>
                        <object>
                           <property name="value">
                              <integer value="8" />
                           </property>
                        </object>
                     </array>
                  </property>
               </object>
            </array>
         </property>
      </object>
   </property>
   <property name="frameworks">
      <string>*</string>
   </property>
   <property name="platforms">
      <string>*</string>
   </property>
   <property name="exclude">
      <string>test</string>
   </property>
</object>
